name: refactor
description: 리팩토링
title: '[REFACTOR]: '
labels: [refactor]
assignees: []
body:
  - type: textarea
    attributes:
      label: 소개
      description: |
        (필수) 코드의 어떤 부분을 리팩토링했는지 알려주세요.
        
        예시:
          - (필수) 버튼 컴포넌트
          - (옵션) 파일 위치: 
            - `./components/Button.tsx`
            - `./components/Button.stories.tsx`
      placeholder: |
        - 버튼 컴포넌트
        - 파일 위치: 
          - `./components/Button.tsx`
          - `./components/Button.stories.tsx`
    validations:
      required: true
  - type: textarea
    attributes:
      label: 목적
      description: |
        (필수) 리팩토링을 하게 된 목적, 배경을 설명해주세요.
        
        예시:
          - 하드코딩한 내용을 변수에 할당하기 위해
          - 기존에 작성한 코드를 추상화하기 위해
    validations:
      required: true
  - type: textarea
    attributes:
      label: 스크린샷
      description: |
        (옵션) 이미지와 같은 미디어 파일을 통해 추가적으로 설명할 내용이 있다면 작성해주세요.
      placeholder: |
        ![파일 이름1](URL)
        파일에 대한 설명
        
        ![파일 이름2](URL)
        파일에 대한 설명
    validations:
      required: false
  - type: textarea
    attributes:
      label: 주의사항
      description: |
        (옵션) 특별히 주의해야할 내용이 있다면 알려주세요.
        
        예시:
          - Windows OS, Chrome 환경에서는 제대로 동작하지 않음.
    validations:
      required: false
