name: storybook-chromatic-deployment
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  issues: write

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: '캐싱'
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys:
            ${{ runner.os }}-node-
      - name: 'Install Dependencies'
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: 'Deploy'
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
      - name: Create or update comment
        if: github.event_name != 'push'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Chromatic build-output
            | Results | |
            | --- | --- |
            | Build result | [Link](${{steps.chromatic.outputs.buildUrl}}) |
            | Storybook preview | [Link](${{steps.chromatic.outputs.storybookUrl}}) |
            | Component count | ${{steps.chromatic.outputs.componentCount}} |
          edit-mode: replace
