name: story-book
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Deploy'
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
